using System.Text.Json;
using System.Text.Json.Nodes;
using TotalGymLogBook.Domain;

// Regenerates the cross-language parity fixtures (docs/adr/0009):
//
//   data/resistance-cases.json     inputs, deterministic
//   data/resistance-expected.json  golden outputs from the C# implementation
//
// Both are committed. The xUnit and vitest suites each compute every case and assert against
// the golden file, so either implementation drifting fails its own suite independently, and an
// intentional formula change shows up as a reviewable diff.
//
// Run:  dotnet run --project tools/GenerateExpected

var repoRoot = FindRepoRoot();
var dataDir = Path.Combine(repoRoot, "data");
var profiles = RailProfileTable.Parse(File.ReadAllText(Path.Combine(dataDir, "rail-profiles.json")));

double[] bodyweights = [110, 145, 180, 235];

(string Name, Func<double, int, ResistanceInputs> Build)[] variants =
[
    ("direct",   (bw, lv) => new ResistanceInputs { BodyweightLb = bw, Level = lv }),
    ("pulley",   (bw, lv) => new ResistanceInputs { BodyweightLb = bw, Level = lv, UsesPulley = true }),
    ("vest20",   (bw, lv) => new ResistanceInputs { BodyweightLb = bw, Level = lv, VestLb = 20 }),
    ("bar10",    (bw, lv) => new ResistanceInputs { BodyweightLb = bw, Level = lv, BarLb = 10 }),
    ("frac70",   (bw, lv) => new ResistanceInputs { BodyweightLb = bw, Level = lv, BodyFraction = 0.70 }),
    ("combined", (bw, lv) => new ResistanceInputs
    {
        BodyweightLb = bw, Level = lv, UsesPulley = true,
        BodyFraction = 0.85, VestLb = 15, BarLb = 5, DirectLoadLb = 5
    }),
];

var cases = new JsonArray();
var expected = new JsonObject();

foreach (var profile in profiles.Profiles.OrderBy(p => p.LevelCount))
{
    for (var level = 1; level <= profile.LevelCount; level++)
    foreach (var bw in bodyweights)
    foreach (var (name, build) in variants)
    {
        var inputs = build(bw, level);
        var id = $"{profile.Id}:L{level}:bw{bw:0}:{name}";

        cases.Add(new JsonObject
        {
            ["id"] = id,
            ["profileId"] = profile.Id,
            ["level"] = level,
            ["bodyweightLb"] = inputs.BodyweightLb,
            ["usesPulley"] = inputs.UsesPulley,
            ["bodyFraction"] = inputs.BodyFraction,
            ["vestLb"] = inputs.VestLb,
            ["barLb"] = inputs.BarLb,
            ["directLoadLb"] = inputs.DirectLoadLb
        });

        expected[id] = ResistanceCalculator.ComputeRounded(profile, inputs);
    }
}

var opts = new JsonSerializerOptions { WriteIndented = true };

var casesDoc = new JsonObject
{
    ["$comment"] =
        "GENERATED by tools/GenerateExpected -- do not hand-edit. Parity test inputs; see docs/adr/0009.",
    ["formulaVersion"] = ResistanceCalculator.FormulaVersion,
    ["cases"] = cases
};

var expectedDoc = new JsonObject
{
    ["$comment"] =
        "GENERATED by tools/GenerateExpected -- do not hand-edit. Golden outputs from the C# "
        + "implementation, rounded to outputDecimals. Both C# and TypeScript assert against this. "
        + "A diff here means the formula changed; make sure that was deliberate.",
    ["formulaVersion"] = ResistanceCalculator.FormulaVersion,
    ["outputDecimals"] = ResistanceCalculator.OutputDecimals,
    ["expected"] = expected
};

File.WriteAllText(Path.Combine(dataDir, "resistance-cases.json"), casesDoc.ToJsonString(opts) + "\n");
File.WriteAllText(Path.Combine(dataDir, "resistance-expected.json"), expectedDoc.ToJsonString(opts) + "\n");

Console.WriteLine($"Wrote {cases.Count} cases across {profiles.Profiles.Count} profiles.");

static string FindRepoRoot()
{
    var dir = new DirectoryInfo(AppContext.BaseDirectory);
    while (dir is not null)
    {
        if (File.Exists(Path.Combine(dir.FullName, "data", "rail-profiles.json"))) return dir.FullName;
        dir = dir.Parent;
    }

    throw new DirectoryNotFoundException("Could not locate the repo root.");
}
